export enum CivilizationsEnum {
  ABBASID = 'abbasid',
  AYYUBIDS = 'ayyubids',
  BYZANTINES = 'byzantines',
  CHINESE = 'chinese',
  DELHI = 'delhi',
  ENGLISH = 'english',
  FRENCH = 'french',
  HRE = 'hre',
  JAPANESE = 'japanese',
  JEANNE_DARC = 'jeannedarc',
  MALIANS = 'malians',
  MONGOLS = 'mongols',
  OOTD = 'orderofthedragon',
  ottomans = 'ottomans',
  RUS = 'rus',
  ZHU_XI = 'zhuxi',
}