export enum CivsBackgroundColors {
  ABBASID = 'abbasid',
  AYYUBIDS = 'ayyubids',
  BYZANTINES = 'rgba(42, 38, 47, 1)',
  CHINESE = 'chinese',
  DELHI = 'rgba(32, 40, 36, 1)',
  ENGLISH = 'english',
  FRENCH = 'rgba(40, 46, 50, 1)',
  HRE = 'rgba(45, 43, 36, 1)',
  JAPANESE = 'japanese',
  JEANNEDARC = 'rgba(42, 42, 42, 1)',
  MALIANS = 'malians',
  MONGOLS = 'mongols',
  OOTD = 'orderofthedragon',
  ottomans = 'ottomans',
  RUS = 'rus',
  ZHUXI = 'zhuxi',
}