export enum CivsAbbreviationsEnum {
  abbasid = 'ab',
  ayyubids = 'ay',
  byzantines = 'by',
  chinese = 'ch',
  delhi = 'de',
  english = 'en',
  french = 'fr',
  hre = 'hr',
  japanese = 'ja',
  jeannedarc = 'je',
  malians = 'ma',
  mongols = 'mo',
  orderofthedragon = 'od',
  ottomans = 'ot',
  rus = 'ru',
  zhuxi = 'zx',
}