import { Unit } from "@domain/entities/unit";

export const WAR_ELEPHANT = {
  id: "war-elephant-3",
  baseId: "war-elephant",
  type: "unit",
  name: "War Elephant",
  pbgid: 136090,
  attribName: "unit_war_elephant_3_sul",
  age: 3,
  civs: ["de"],
  description:
    "Heavy cavalry effective against cavalry, siege engines, walls, and buildings.\n+ High health and armor\n+ Mounted with an advanced Spearman\n+ Capable of attacking Stone Walls\n- Slow movement speed",
  classes: ["heavy", "melee", "cavalry", "elephant"],
  displayClasses: ["Heavy Melee Cavalry", "Elephant"],
  unique: true,
  costs: {
    food: 400,
    wood: 0,
    stone: 0,
    gold: 350,
    vizier: 0,
    oliveoil: 0,
    total: 750,
    popcap: 3,
    time: 60,
  },
  producedBy: ["stable"],
  icon: "https://data.aoe4world.com/images/units/war-elephant-3.png",
  hitpoints: 850,
  weapons: [
    {
      name: "Tusks",
      type: "melee",
      damage: 50,
      speed: 2.875,
      range: {
        min: 0,
        max: 1,
      },
      modifiers: [
        {
          property: "meleeAttack",
          target: {
            class: [["building"]],
          },
          effect: "change",
          value: 45,
          type: "passive",
        },
      ],
      durations: {
        aim: 0,
        windup: 0.75,
        attack: 0.125,
        winddown: 2,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 0,
      },
      attribName: "weapon_war_elephant_melee_3_sul",
      pbgid: 184643,
    },
    {
      name: "Spear",
      type: "melee",
      damage: 25,
      speed: 1.875,
      range: {
        min: 0,
        max: 1.25,
      },
      modifiers: [
        {
          property: "meleeAttack",
          target: {
            class: [["cavalry"]],
          },
          effect: "change",
          value: 40,
          type: "passive",
        },
      ],
      durations: {
        aim: 0,
        windup: 0.25,
        attack: 0.125,
        winddown: 0.75,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 0.75,
      },
      attribName: "weapon_war_elephant_spear_3_sul",
      pbgid: 144673,
    },
  ],
  armor: [
    {
      type: "melee",
      value: 4,
    },
    {
      type: "ranged",
      value: 5,
    },
  ],
  sight: {
    line: 36,
    height: 10,
  },
  movement: {
    speed: 1,
  },
} as unknown as Unit;

export const ROYAL_KNIGHT = {
  id: "royal-knight-4",
  baseId: "royal-knight",
  type: "unit",
  name: "Elite Royal Knight",
  pbgid: 132280,
  attribName: "unit_knight_4_fre",
  age: 4,
  civs: ["fr"],
  description:
    "Gain bonus damage for 5 seconds after charging. Effective against most units.\n+ Heavy armor\n+ Strong in melee combat\n- Countered by Spearmen and Crossbowmen",
  classes: ["heavy", "melee", "cavalry"],
  displayClasses: ["Heavy Melee Cavalry"],
  unique: true,
  costs: {
    food: 140,
    wood: 0,
    stone: 0,
    gold: 100,
    vizier: 0,
    oliveoil: 0,
    total: 240,
    popcap: 1,
    time: 35,
  },
  producedBy: ["school-of-cavalry", "stable"],
  icon: "https://data.aoe4world.com/images/units/royal-knight-4.png",
  hitpoints: 270,
  weapons: [
    {
      name: "Sword",
      type: "melee",
      damage: 29,
      speed: 1.5,
      range: {
        min: 0,
        max: 0.2875,
      },
      modifiers: [],
      durations: {
        aim: 0,
        windup: 0.5,
        attack: 0.125,
        winddown: 0,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 0.875,
      },
      attribName: "weapon_knight_4",
      pbgid: 127822,
    },
    {
      name: "Torch",
      type: "fire",
      damage: 10,
      speed: 2.125,
      range: {
        min: 0,
        max: 1.25,
      },
      modifiers: [],
      durations: {
        aim: 0,
        windup: 0.75,
        attack: 0.125,
        winddown: 0,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 1.25,
      },
      attribName: "weapon_torch_horseman",
      pbgid: 127935,
    },
  ],
  armor: [
    {
      type: "melee",
      value: 5,
    },
    {
      type: "ranged",
      value: 5,
    },
  ],
  sight: {
    line: 28,
    height: 10,
  },
  movement: {
    speed: 1.625,
  },
} as unknown as Unit;

export const ARCHER = {
  id: "archer-4",
  baseId: "archer",
  type: "unit",
  name: "Elite Archer",
  pbgid: 4097251,
  attribName: "unit_archer_4_byz",
  age: 4,
  civs: ["by"],
  description:
    "Cheap ranged infantry with good damage vs. unarmored targets.\n+ High rate of fire\n- Weak against armored targets\n- Countered by Horsemen",
  classes: ["light", "ranged", "infantry"],
  displayClasses: ["Light Ranged Infantry"],
  unique: false,
  costs: {
    food: 30,
    wood: 50,
    stone: 0,
    gold: 0,
    vizier: 0,
    oliveoil: 0,
    total: 80,
    popcap: 1,
    time: 15,
  },
  producedBy: ["archery-range"],
  icon: "https://data.aoe4world.com/images/units/archer-4.png",
  hitpoints: 95,
  weapons: [
    {
      name: "Bow",
      type: "ranged",
      damage: 8,
      speed: 1.625,
      range: {
        min: 0,
        max: 5,
      },
      modifiers: [
        {
          property: "rangedAttack",
          target: {
            class: [["light", "melee", "infantry"]],
          },
          effect: "change",
          value: 8,
          type: "passive",
        },
      ],
      durations: {
        aim: 0.25,
        windup: 0,
        attack: 0.125,
        winddown: 0.5,
        reload: 0.75,
        setup: 0,
        teardown: 0,
        cooldown: 0,
      },
      attribName: "weapon_archer_4",
      pbgid: 127829,
    },
  ],
  armor: [],
  sight: {
    line: 36,
    height: 10,
  },
  movement: {
    speed: 1.25,
  },
} as unknown as Unit;

export const LANDSKENETCH = {
  id: "landsknecht-4",
  baseId: "landsknecht",
  type: "unit",
  name: "Elite Landsknecht",
  pbgid: 168401,
  attribName: "unit_landsknecht_4_hre",
  age: 4,
  civs: ["hr"],
  description:
    "Brave unarmored infantry with an enormous two-handed sword, effective in mixed armies.\n+ Melee attack deals area damage\n- Low health\n- Countered by Archers",
  classes: ["light", "melee", "infantry"],
  displayClasses: ["Light Melee Infantry"],
  unique: true,
  costs: {
    food: 60,
    wood: 0,
    stone: 0,
    gold: 100,
    vizier: 0,
    oliveoil: 0,
    total: 160,
    popcap: 1,
    time: 22.5,
  },
  producedBy: ["barracks", "burgrave-palace"],
  icon: "https://data.aoe4world.com/images/units/landsknecht-4.png",
  hitpoints: 100,
  weapons: [
    {
      name: "Zweihander",
      type: "melee",
      damage: 20,
      speed: 1.375,
      range: {
        min: 0,
        max: 0.295,
      },
      modifiers: [],
      durations: {
        aim: 0,
        windup: 0.5,
        attack: 0.125,
        winddown: 0.75,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 0,
      },
      attribName: "weapon_landsknecht_4_hre",
      pbgid: 184609,
    },
    {
      name: "Torch",
      type: "fire",
      damage: 10,
      speed: 2.125,
      range: {
        min: 0,
        max: 1.25,
      },
      modifiers: [],
      durations: {
        aim: 0,
        windup: 0.75,
        attack: 0.125,
        winddown: 0,
        reload: 0,
        setup: 0,
        teardown: 0,
        cooldown: 1.25,
      },
      attribName: "weapon_torch",
      pbgid: 123518,
    },
  ],
  armor: [],
  sight: {
    line: 36,
    height: 10,
  },
  movement: {
    speed: 1.25,
  },
} as unknown as Unit;
